### PR TITLE
Add socket timeout

### PR DESCRIPTION
**Pull request by svenXY**
Hi,

I was also missing the possibility of a socket timeout if a zabbix server is unavailable, so I took the liberty to implement it here.

Thanks for your nice module!

Sven

### CODE REVIEW

**Comment by adubkov** [comment]
@svenXY Thanks.

Looks good to me.

@maksim77 Please review it as well, then we can merge it. I will fix tests issue with separate PR.

**Comment by sriccio** [comment]
@svenXY looks like there are changes on your commit that doesn't pass the checks.

```
pyzabbix/sender.py:361:13: E303 too many blank lines (2)
pyzabbix/sender.py:366:80: E501 line too long (119 > 79 characters)
```

maybe you can address them so it can be merged ?

**Comment by sriccio** [comment]
@adubkov @maksim77 

Hi, could this be merged and a new version deployed so we can install it via pip ? :)

That's a feature current 1.1.3 really lacks.

**Comment by nijel** [comment]
Hi, are there any plans for releasing this to pypi?

**Comment by adubkov** [comment]
Hi, yes. Will do it this week.

**Pull request merged**
