### PR TITLE
filter to hide password and auth_token in logs and exceptions

### PR DESCRIPTION
**Pull request by v-zhuravlev**
Hi, I added logging filter to mask passwords and auth tokens using `********` in case they are printed in logger or exceptions
with help of `logging.Filter` class https://docs.python.org/3/library/logging.html#logging.Filter

Here is an example:
```python
import sys
import logging
from pyzabbix.api import ZabbixAPI

# Create ZabbixAPI class instance
logger = logging.getLogger("pyzabbix")
logger.setLevel(logging.DEBUG)
handler = logging.StreamHandler(sys.stdout)
logger.addHandler(handler)

with ZabbixAPI(url='http://localhost', user='Admin', password='zabbix') as zapi:

    # Get all monitored hosts(intentionally broken call to raise exception)
    result1 = zapi.host2.get(monitored_hosts=1, output='extend')
```
would give you the output:
```python
ZabbixAPI.login(Admin,********)
Call user.login method
urllib2.Request(http://localhost/api_jsonrpc.php, {"jsonrpc": "2.0", "method": "user.login", "params": {"user": "Admin", "password": "********"}, "id": "1"})
Response Body: {
    "jsonrpc": "2.0",
    "result": "********",
    "id": "1"
}
JSON-PRC Server: http://localhost/api_jsonrpc.php
Call host2.get method
urllib2.Request(http://localhost/api_jsonrpc.php, {"jsonrpc": "2.0", "method": "host2.get", "params": {"monitored_hosts": 1, "output": "extend"}, "id": "1", "auth": "********"})
Response Body: {
    "jsonrpc": "2.0",
    "error": {
        "code": -32602,
        "message": "Invalid params.",
        "data": "Incorrect API \"host2\"."
    },
    "id": "1"
}
ZabbixAPI.logout()
Call user.logout method
urllib2.Request(http://localhost/api_jsonrpc.php, {"jsonrpc": "2.0", "method": "user.logout", "params": {}, "id": "1", "auth": "********"})
Response Body: {
    "jsonrpc": "2.0",
    "result": true,
    "id": "1"
}
Traceback (most recent call last):
  File ".\simple_test.py", line 15, in <module>
    result1 = zapi.host2.get(monitored_hosts=1, output='extend')
  File "C:\temp\repos\py-zabbix\pyzabbix\api.py", line 92, in fn
    args or kwargs
  File "C:\temp\repos\py-zabbix\pyzabbix\api.py", line 280, in do_request
    raise ZabbixAPIException(err)
pyzabbix.api.ZabbixAPIException: {'code': -32602, 'message': 'Invalid params.', 'data': 'Incorrect API "host2".', 'json': "{'jsonrpc': '2.0', 'method': 'host2.get', 'params': {'monitored_hosts': 1, 'output': 'extend'}, 'id': '1', 'auth': '********'}"}
```

Logging filter is only applied if logger is used. Otherwise, no additional overhead on string manipulation is expected, as far as I see it.

Please tell what you think. I can refactor this and add tests.

### CODE REVIEW

**Comment by v-zhuravlev** [comment]
@adubkov, would be great to hear what you think, when you have a time.

**Comment by adubkov** [comment]
@v-zhuravlev I like that idea, in fact it is real security issue now. Could you add tests to verify that it actually hide values as expected?

**Comment by v-zhuravlev** [comment]
added tests and updated docs. Please check

**Comment by v-zhuravlev** [comment]
@adubkov , sorry for disturbing you again :)

**Pull request merged**
